from __future__ import annotations
import json
from pathlib import Path
OUT=Path("docs/stocklens8_falsification_report.json")
def _load(path):
 p=Path(path);return json.loads(p.read_text()) if p.exists() else {}
def build(out=OUT):
 adversarial=_load("docs/backtest_adversarial.json");regimes=_load("docs/backtest_regimes.json");concentration=_load("docs/backtest_return_concentration.json");topday=_load("docs/backtest_topday_ablation.json");yearly=_load("docs/backtest_calendar_year_fragility.json");path=_load("docs/backtest_path_fragility.json")
 tqqq=_load("research/tqqq_reality_check.json");hybrid_concentration=_load("research/hybrid_return_concentration.json");rolling_distribution=_load("research/hybrid_rolling_distribution.json");robustness_gate=_load("research/robustness_evidence_gate.json")
 execution_rolling=_load("research/execution_realistic_rolling_distribution.json");execution_rolling_stress=_load("research/execution_realistic_rolling_stress_grid.json");long_horizon=_load("research/long_horizon_independence_stress.json");decade_breaker=_load("research/decade_breaker_stress.json");decade_boundary=_load("research/decade_claim_boundary.json")
 instrument_reality=_load("research/leveraged_instrument_reality_check.json");financing_reality=_load("research/financed_1_25x_reality_check.json");parameter_start_sensitivity=_load("research/frozen8_parameter_start_sensitivity.json");frozen8_sensitivity=_load("research/frozen8_sensitivity.json")
 sources={"cost_delay":adversarial.get("status"),"regimes":regimes.get("status"),"return_concentration":concentration.get("status"),"topday_ablation":topday.get("status"),"calendar_year_fragility":yearly.get("status"),"path_fragility":path.get("status"),"tqqq_reality_check":tqqq.get("status"),"hybrid_return_concentration":hybrid_concentration.get("status"),"hybrid_rolling_distribution":rolling_distribution.get("status"),"robustness_evidence_gate":robustness_gate.get("status"),"execution_realistic_rolling":execution_rolling.get("status"),"execution_realistic_rolling_stress_grid":execution_rolling_stress.get("status"),"long_horizon_independence_stress":long_horizon.get("status"),"decade_breaker_stress":decade_breaker.get("status"),"decade_claim_boundary":decade_boundary.get("status"),"leveraged_instrument_reality":instrument_reality.get("status"),"financed_1_25x_reality":financing_reality.get("status"),"parameter_start_sensitivity":parameter_start_sensitivity.get("status"),"frozen8_sensitivity":frozen8_sensitivity.get("status")}
 hybrid=tqqq.get("hybrid_actual_l3_stress",{})
 result={"schema_version":2,"kind":"FROZEN_STOCKLENS_8_FALSIFICATION_REPORT","status":"COMPLETE" if all(v=="PASS" for v in sources.values()) else "INCOMPLETE","frozen_model_mutated":False,"retuning_authorized":False,"automatic_promotion":False,"source_status":sources,"execution_realism":{"synthetic_baseline":adversarial.get("baseline"),"synthetic_stresses":adversarial.get("stresses",[]),"observed_tqqq_tracking":tqqq.get("three_x_tracking"),"hybrid_actual_l3_cost_ladder":hybrid.get("cost_ladder",[]),"hybrid_actual_l3_delay":hybrid.get("decision_delay",[]),"observed_3x_2x_instrument_reality":instrument_reality,"financed_1_25x_reality":financing_reality,"claim_boundary":tqqq.get("claim_boundary")},"robustness":{"regimes":regimes.get("regimes",{}),"return_concentration":{k:v for k,v in concentration.items() if k.startswith("top") or k in ("sessions","positive_sessions")},"topday_ablation":topday.get("cases",[]),"calendar_year_coverage":yearly.get("coverage"),"leave_one_year_out":yearly.get("leave_one_year_out",[]),"path_fragility":path,"hybrid_return_concentration":hybrid_concentration,"hybrid_rolling_distribution":rolling_distribution,"execution_realistic_rolling_distribution":execution_rolling,"execution_realistic_rolling_stress_grid":execution_rolling_stress,"long_horizon_independence_stress":long_horizon,"decade_breaker_stress":decade_breaker,"decade_claim_boundary":decade_boundary,"robustness_evidence_gate":robustness_gate,"parameter_start_sensitivity":parameter_start_sensitivity,"frozen8_sensitivity":frozen8_sensitivity},"interpretation":"Frozen 8.0 falsification surface. COMPLETE means required diagnostics executed; it is not an investability verdict. Negative evidence is retained and no result may retune or promote frozen 8.0."}
 Path(out).write_text(json.dumps(result,indent=2)+"\n");return result
if __name__=="__main__":print(json.dumps(build(),indent=2))
